apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
  name: openshift-storage
  labels:
    name: openshift-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PreSync
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: odf-cli-job-sa-role
rules:
  - apiGroups:
    - "*"
    resources: ["nodes", "storageclusters"]
    verbs:
    - list
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odf-cli-gitops-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odf-cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-odf-sa
    namespace: openshift-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-odf-sa
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: wait-ocs
  namespace: openshift-storage
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              echo -n "Waiting for the storage cluster to be ready."
              RTN=1
              while [ $RTN -ne 0 ];
              do
                oc get storagecluster ocs-storagecluster -n openshift-storage | grep Ready > /dev/null
                RTN=$?
                if [ $RTN -ne 0]; then
                  echo -n "."
                  sleep $SLEEP
                fi
              done
          imagePullPolicy: IfNotPresent
          name: assisted-service-pause-job
          env:
          - name: SLEEP
            value: "10"
      restartPolicy: Never
      serviceAccount: cli-odf-sa
