---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1
  namespace: volante-cars-lab
  labels:
    cluster-name: volante-nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.57.121
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2057::121
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.57.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2057::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:77:DA
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2
  namespace: volante-cars-lab
  labels:
    cluster-name: volante-nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.57.122
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2057::122
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.57.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2057::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:D0:D7
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3
  namespace: volante-cars-lab
  labels:
    cluster-name: volante-nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.57.123
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2057::123
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.57.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2057::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:A7:53
