---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: volante-cars-lab
namePrefix: volante-cars-lab-

bases:
  - ../../base

 # environment specific
patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'volante-cars-lab'
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: 'volante-cars-lab'
  - target:
      kind: ClusterDeployment
    path: ./patches/cluster-deployment.yaml
resources:
 # whole yaml is environment specific
 - 00-aci.yaml
