---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: volante-cars-lab
#namePrefix: volante-cars-lab-

bases:
  - ../../base

 # environment specific
patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'volante-cars-lab'
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: 'volante-cars-lab'
  - target:
      kind: ClusterDeployment
    path: ./patches/cluster-deployment.yaml
  - target:
      kind: KlusterletAddonConfig
    path: ./patches/klusterlet-addon-config.yaml
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab'
  - target:
      kind: InfraEnv
    path: ./patches/infra-env.yaml
  - target:
      kind: BareMetalHost
      name: super1
    path: ./patches/bmh-super1.yaml
  - target:
      kind: BareMetalHost
      name: super2
    path: ./patches/bmh-super2.yaml
  - target:
      kind: BareMetalHost
      name: super3
    path: ./patches/bmh-super3.yaml
resources:
 # whole yaml is environment specific dont use patches
 - 02-aci.yaml
 - 07-nmstate.yaml
