---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    #argocd.argoproj.io/sync-wave: "-1"
    #argocd.argoproj.io/hook: PreSync
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: storage-cli-job-sa-role2
rules:
  - apiGroups:
    - "*"
    resources: ["nodes", "storageclasses"]
    verbs:
    - list
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-cli-gitops-rolebinding2
  annotations:
    #argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-cli-job-sa-role2
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: openshift-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: openshift-storage
  annotations:
    #argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/sync-wave: "-1"
