apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Set up OpenShift Local Storage Operator
  - ./00-lso
  # add labels
  - ./01-lv
  # Set Up OpenShift Data Fabric
  #- ./04-odf
