---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster-deployment
  namespace: patch-me
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  baseDomain: patch-me
  clusterName: patch-me
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: patch-me
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: patch-me
  pullSecretRef:
    name: assisted-deployment-pull-secret
