---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: infraenv
  namespace: patch-me
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    argocd.argoproj.io/sync-wave: "6"
spec:
  additionalNTPSources:
    - patch-me
    - patch-me
  clusterRef:
    name: patch-me
    namespace: patch-me
  sshAuthorizedKey: patch-me
  #agentLabelSelector:
  #  matchLabels:
  #    cluster-name: patch-me
  pullSecretRef:
    name: patch-me
  # Customized network configuration
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: patch-me
