apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
namespace: sealed-secrets

bases:
- github.com/redhat-cop/gitops-catalog/sealed-secrets-operator/overlays/default
