apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Set up OpenShift Local Storage Operator
  - ./00-lso
  # add labels
  - ./01-lv/overlays/default
  # Set Up OpenShift Data Fabric
  - ./02-odf
  # consume data fabric with assisted service
  - ./03-assisted-service
