apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-clusters
  namespace: openshift-gitops
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: spaceName
spec:
  generators:
  - git:
      repoURL: https://github.com/jnunyez/cluster-config
      revision: main
      directories:
      - path: manifests/workload-clusters/overlays/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/jnunyez/cluster-config
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
