---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # Red Hat Advanced Cluster Manager for Kubernetes
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/overlays/release-2.5?ref=main
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base?ref=main
