apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/acm/00-operator
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/acm/01-instance
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true