apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/core/00-gitops/
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true