apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-volume-setup
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/storage/01-lv/
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
