apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: 
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/storage/04-odf
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true