apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/workload-clusters/overlays/volante
    repoURL: https://github.com/jnunyez/cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
